//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common
{
    
    
    /// <summary>
    /// >> ProgramState
    /// </summary>
    public enum ProgramState
    {
        
        /// <summary>
        /// >> Uninitialized
        /// </summary>
        Uninitialized = 0,
        
        /// <summary>
        /// >> Initialized
        /// </summary>
        Initialized = 1,
    }
    
    /// <summary>
    /// >> 562 - Variant[gear_common.ProgramState]
    /// </summary>
    public sealed class EnumProgramState : BaseEnumExt<ProgramState, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId, BaseVoid>
    {
    }
}
