//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common
{
    
    
    /// <summary>
    /// >> Program
    /// </summary>
    public enum Program
    {
        
        /// <summary>
        /// >> Active
        /// </summary>
        Active = 0,
        
        /// <summary>
        /// >> Exited
        /// </summary>
        Exited = 1,
        
        /// <summary>
        /// >> Terminated
        /// </summary>
        Terminated = 2,
    }
    
    /// <summary>
    /// >> 554 - Variant[gear_common.Program]
    /// </summary>
    public sealed class EnumProgram : BaseEnumExt<Program, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.ActiveProgram, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId>
    {
    }
}
