//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.paused_program_storage
{
    
    
    /// <summary>
    /// >> 566 - Composite[gear_common.paused_program_storage.ResumeSession]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class ResumeSession : BaseType
    {
        
        /// <summary>
        /// >> page_count
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.U32 PageCount { get; set; }
        /// <summary>
        /// >> user
        /// </summary>
        public Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32 User { get; set; }
        /// <summary>
        /// >> program_id
        /// </summary>
        public Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId ProgramId { get; set; }
        /// <summary>
        /// >> allocations
        /// </summary>
        public Substrate.Vara.NET.NetApiExt.Generated.Types.Base.BTreeSetT1 Allocations { get; set; }
        /// <summary>
        /// >> code_hash
        /// </summary>
        public Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId CodeHash { get; set; }
        /// <summary>
        /// >> end_block
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.U32 EndBlock { get; set; }
        
        /// <inheritdoc/>
        public override string TypeName()
        {
            return "ResumeSession";
        }
        
        /// <inheritdoc/>
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(PageCount.Encode());
            result.AddRange(User.Encode());
            result.AddRange(ProgramId.Encode());
            result.AddRange(Allocations.Encode());
            result.AddRange(CodeHash.Encode());
            result.AddRange(EndBlock.Encode());
            return result.ToArray();
        }
        
        /// <inheritdoc/>
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            PageCount = new Substrate.NetApi.Model.Types.Primitive.U32();
            PageCount.Decode(byteArray, ref p);
            User = new Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32();
            User.Decode(byteArray, ref p);
            ProgramId = new Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId();
            ProgramId.Decode(byteArray, ref p);
            Allocations = new Substrate.Vara.NET.NetApiExt.Generated.Types.Base.BTreeSetT1();
            Allocations.Decode(byteArray, ref p);
            CodeHash = new Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId();
            CodeHash.Decode(byteArray, ref p);
            EndBlock = new Substrate.NetApi.Model.Types.Primitive.U32();
            EndBlock.Decode(byteArray, ref p);
            var bytesLength = p - start;
            TypeSize = bytesLength;
            Bytes = new byte[bytesLength];
            System.Array.Copy(byteArray, start, Bytes, 0, bytesLength);
        }
    }
}
