//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_gear_program.pallet
{
    
    
    /// <summary>
    /// >> Error
    /// The `Error` enum of this pallet.
    /// </summary>
    public enum Error
    {
        
        /// <summary>
        /// >> DuplicateItem
        /// </summary>
        DuplicateItem = 0,
        
        /// <summary>
        /// >> ProgramNotFound
        /// </summary>
        ProgramNotFound = 1,
        
        /// <summary>
        /// >> NotActiveProgram
        /// </summary>
        NotActiveProgram = 2,
        
        /// <summary>
        /// >> CannotFindDataForPage
        /// </summary>
        CannotFindDataForPage = 3,
        
        /// <summary>
        /// >> ResumeSessionNotFound
        /// </summary>
        ResumeSessionNotFound = 4,
        
        /// <summary>
        /// >> NotSessionOwner
        /// </summary>
        NotSessionOwner = 5,
        
        /// <summary>
        /// >> ResumeSessionFailed
        /// </summary>
        ResumeSessionFailed = 6,
        
        /// <summary>
        /// >> ProgramCodeNotFound
        /// </summary>
        ProgramCodeNotFound = 7,
        
        /// <summary>
        /// >> DuplicateResumeSession
        /// </summary>
        DuplicateResumeSession = 8,
    }
    
    /// <summary>
    /// >> 567 - Variant[pallet_gear_program.pallet.Error]
    /// The `Error` enum of this pallet.
    /// </summary>
    public sealed class EnumError : BaseEnum<Error>
    {
    }
}
