//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_multisig.pallet
{
    
    
    /// <summary>
    /// >> Event
    /// The `Event` enum of this pallet
    /// </summary>
    public enum Event
    {
        
        /// <summary>
        /// >> NewMultisig
        /// A new multisig operation has begun.
        /// </summary>
        NewMultisig = 0,
        
        /// <summary>
        /// >> MultisigApproval
        /// A multisig operation has been approved by someone.
        /// </summary>
        MultisigApproval = 1,
        
        /// <summary>
        /// >> MultisigExecuted
        /// A multisig operation has been executed.
        /// </summary>
        MultisigExecuted = 2,
        
        /// <summary>
        /// >> MultisigCancelled
        /// A multisig operation has been cancelled.
        /// </summary>
        MultisigCancelled = 3,
    }
    
    /// <summary>
    /// >> 293 - Variant[pallet_multisig.pallet.Event]
    /// The `Event` enum of this pallet
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Types.Base.Arr32U8>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_multisig.Timepoint, Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Types.Base.Arr32U8>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_multisig.Timepoint, Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Types.Base.Arr32U8, Substrate.Vara.NET.NetApiExt.Generated.Types.Base.EnumResult>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_multisig.Timepoint, Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Types.Base.Arr32U8>>
    {
    }
}
