//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.code
{
    
    
    /// <summary>
    /// >> 549 - Composite[gear_core.code.InstrumentedCode]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class InstrumentedCode : BaseType
    {
        
        /// <summary>
        /// >> code
        /// </summary>
        public Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8> Code { get; set; }
        /// <summary>
        /// >> original_code_len
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.U32 OriginalCodeLen { get; set; }
        /// <summary>
        /// >> exports
        /// </summary>
        public Substrate.Vara.NET.NetApiExt.Generated.Types.Base.BTreeSetT3 Exports { get; set; }
        /// <summary>
        /// >> static_pages
        /// </summary>
        public Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.pages.WasmPage StaticPages { get; set; }
        /// <summary>
        /// >> version
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.U32 Version { get; set; }
        
        /// <inheritdoc/>
        public override string TypeName()
        {
            return "InstrumentedCode";
        }
        
        /// <inheritdoc/>
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Code.Encode());
            result.AddRange(OriginalCodeLen.Encode());
            result.AddRange(Exports.Encode());
            result.AddRange(StaticPages.Encode());
            result.AddRange(Version.Encode());
            return result.ToArray();
        }
        
        /// <inheritdoc/>
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Code = new Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>();
            Code.Decode(byteArray, ref p);
            OriginalCodeLen = new Substrate.NetApi.Model.Types.Primitive.U32();
            OriginalCodeLen.Decode(byteArray, ref p);
            Exports = new Substrate.Vara.NET.NetApiExt.Generated.Types.Base.BTreeSetT3();
            Exports.Decode(byteArray, ref p);
            StaticPages = new Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.pages.WasmPage();
            StaticPages.Decode(byteArray, ref p);
            Version = new Substrate.NetApi.Model.Types.Primitive.U32();
            Version.Decode(byteArray, ref p);
            var bytesLength = p - start;
            TypeSize = bytesLength;
            Bytes = new byte[bytesLength];
            System.Array.Copy(byteArray, start, Bytes, 0, bytesLength);
        }
    }
}
