//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi;
using Substrate.NetApi.Model.Extrinsics;
using Substrate.NetApi.Model.Meta;
using Substrate.NetApi.Model.Types;
using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace Substrate.Vara.NET.NetApiExt.Generated.Storage
{
    
    
    /// <summary>
    /// >> GearVoucherStorage
    /// </summary>
    public sealed class GearVoucherStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateClientExt _client;
        
        /// <summary>
        /// >> GearVoucherStorage Constructor
        /// </summary>
        public GearVoucherStorage(SubstrateClientExt client)
        {
            this._client = client;
        }
    }
    
    /// <summary>
    /// >> GearVoucherCalls
    /// </summary>
    public sealed class GearVoucherCalls
    {
        
        /// <summary>
        /// >> issue
        /// Contains a variant per dispatchable extrinsic that this pallet has.
        /// </summary>
        public static Method Issue(Substrate.Vara.NET.NetApiExt.Generated.Model.sp_runtime.multiaddress.EnumMultiAddress to, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId program, Substrate.NetApi.Model.Types.Primitive.U128 value)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(to.Encode());
            byteArray.AddRange(program.Encode());
            byteArray.AddRange(value.Encode());
            return new Method(107, "GearVoucher", 0, "issue", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> call
        /// Contains a variant per dispatchable extrinsic that this pallet has.
        /// </summary>
        public static Method Call(Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_gear_voucher.EnumPrepaidCall call)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(call.Encode());
            return new Method(107, "GearVoucher", 1, "call", byteArray.ToArray());
        }
    }
    
    /// <summary>
    /// >> GearVoucherConstants
    /// </summary>
    public sealed class GearVoucherConstants
    {
        
        /// <summary>
        /// >> PalletId
        ///  The pallet id, used for deriving its sovereign account ID.
        /// </summary>
        public Substrate.Vara.NET.NetApiExt.Generated.Model.frame_support.PalletId PalletId()
        {
            var result = new Substrate.Vara.NET.NetApiExt.Generated.Model.frame_support.PalletId();
            result.Create("0x70792F766F756368");
            return result;
        }
    }
    
    /// <summary>
    /// >> GearVoucherErrors
    /// </summary>
    public enum GearVoucherErrors
    {
        
        /// <summary>
        /// >> FailureToCreateVoucher
        /// </summary>
        FailureToCreateVoucher,
        
        /// <summary>
        /// >> FailureToRedeemVoucher
        /// </summary>
        FailureToRedeemVoucher,
    }
}
