//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi;
using Substrate.NetApi.Model.Extrinsics;
using Substrate.NetApi.Model.Meta;
using Substrate.NetApi.Model.Types;
using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace Substrate.Vara.NET.NetApiExt.Generated.Storage
{
    
    
    /// <summary>
    /// >> GearProgramStorage
    /// </summary>
    public sealed class GearProgramStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateClientExt _client;
        
        /// <summary>
        /// >> GearProgramStorage Constructor
        /// </summary>
        public GearProgramStorage(SubstrateClientExt client)
        {
            this._client = client;
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "CodeStorage"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId), typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.code.InstrumentedCode)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "CodeLenStorage"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId), typeof(Substrate.NetApi.Model.Types.Primitive.U32)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "OriginalCodeStorage"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId), typeof(Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "MetadataStorage"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId), typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.CodeMetadata)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "ProgramStorage"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId), typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.EnumProgram)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "MemoryPageStorage"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity,
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, typeof(Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.pages.GearPage>), typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.memory.PageBuf)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "WaitingInitStorage"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId), typeof(Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId>)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "PausedProgramStorage"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId), typeof(Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Model.Types.Primitive.U32, Substrate.Vara.NET.NetApiExt.Generated.Model.primitive_types.H256>)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "ResumeSessionsNonce"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(null, null, typeof(Substrate.NetApi.Model.Types.Primitive.U128)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "ResumeSessions"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, typeof(Substrate.NetApi.Model.Types.Primitive.U128), typeof(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.paused_program_storage.ResumeSession)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("GearProgram", "SessionMemoryPages"), new System.Tuple<Substrate.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                            Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, typeof(Substrate.NetApi.Model.Types.Primitive.U128), typeof(Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.pages.GearPage, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.memory.PageBuf>>)));
        }
        
        /// <summary>
        /// >> CodeStorageParams
        /// </summary>
        public static string CodeStorageParams(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId key)
        {
            return RequestGenerator.GetStorage("GearProgram", "CodeStorage", Substrate.NetApi.Model.Meta.Storage.Type.Map, new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, new Substrate.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> CodeStorageDefault
        /// Default value as hex string
        /// </summary>
        public static string CodeStorageDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> CodeStorage
        /// </summary>
        public async Task<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.code.InstrumentedCode> CodeStorage(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId key, string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.CodeStorageParams(key);
            var result = await _client.GetStorageAsync<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.code.InstrumentedCode>(parameters, blockhash, token);
            return result;
        }
        
        /// <summary>
        /// >> CodeLenStorageParams
        /// </summary>
        public static string CodeLenStorageParams(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId key)
        {
            return RequestGenerator.GetStorage("GearProgram", "CodeLenStorage", Substrate.NetApi.Model.Meta.Storage.Type.Map, new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, new Substrate.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> CodeLenStorageDefault
        /// Default value as hex string
        /// </summary>
        public static string CodeLenStorageDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> CodeLenStorage
        /// </summary>
        public async Task<Substrate.NetApi.Model.Types.Primitive.U32> CodeLenStorage(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId key, string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.CodeLenStorageParams(key);
            var result = await _client.GetStorageAsync<Substrate.NetApi.Model.Types.Primitive.U32>(parameters, blockhash, token);
            return result;
        }
        
        /// <summary>
        /// >> OriginalCodeStorageParams
        /// </summary>
        public static string OriginalCodeStorageParams(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId key)
        {
            return RequestGenerator.GetStorage("GearProgram", "OriginalCodeStorage", Substrate.NetApi.Model.Meta.Storage.Type.Map, new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, new Substrate.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> OriginalCodeStorageDefault
        /// Default value as hex string
        /// </summary>
        public static string OriginalCodeStorageDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> OriginalCodeStorage
        /// </summary>
        public async Task<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>> OriginalCodeStorage(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId key, string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.OriginalCodeStorageParams(key);
            var result = await _client.GetStorageAsync<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>>(parameters, blockhash, token);
            return result;
        }
        
        /// <summary>
        /// >> MetadataStorageParams
        /// </summary>
        public static string MetadataStorageParams(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId key)
        {
            return RequestGenerator.GetStorage("GearProgram", "MetadataStorage", Substrate.NetApi.Model.Meta.Storage.Type.Map, new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, new Substrate.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> MetadataStorageDefault
        /// Default value as hex string
        /// </summary>
        public static string MetadataStorageDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> MetadataStorage
        /// </summary>
        public async Task<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.CodeMetadata> MetadataStorage(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId key, string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.MetadataStorageParams(key);
            var result = await _client.GetStorageAsync<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.CodeMetadata>(parameters, blockhash, token);
            return result;
        }
        
        /// <summary>
        /// >> ProgramStorageParams
        /// </summary>
        public static string ProgramStorageParams(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId key)
        {
            return RequestGenerator.GetStorage("GearProgram", "ProgramStorage", Substrate.NetApi.Model.Meta.Storage.Type.Map, new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, new Substrate.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> ProgramStorageDefault
        /// Default value as hex string
        /// </summary>
        public static string ProgramStorageDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> ProgramStorage
        /// </summary>
        public async Task<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.EnumProgram> ProgramStorage(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId key, string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.ProgramStorageParams(key);
            var result = await _client.GetStorageAsync<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.EnumProgram>(parameters, blockhash, token);
            return result;
        }
        
        /// <summary>
        /// >> MemoryPageStorageParams
        /// </summary>
        public static string MemoryPageStorageParams(Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.pages.GearPage> key)
        {
            return RequestGenerator.GetStorage("GearProgram", "MemoryPageStorage", Substrate.NetApi.Model.Meta.Storage.Type.Map, new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity,
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, key.Value);
        }
        
        /// <summary>
        /// >> MemoryPageStorageDefault
        /// Default value as hex string
        /// </summary>
        public static string MemoryPageStorageDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> MemoryPageStorage
        /// </summary>
        public async Task<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.memory.PageBuf> MemoryPageStorage(Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.pages.GearPage> key, string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.MemoryPageStorageParams(key);
            var result = await _client.GetStorageAsync<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.memory.PageBuf>(parameters, blockhash, token);
            return result;
        }
        
        /// <summary>
        /// >> WaitingInitStorageParams
        /// </summary>
        public static string WaitingInitStorageParams(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId key)
        {
            return RequestGenerator.GetStorage("GearProgram", "WaitingInitStorage", Substrate.NetApi.Model.Meta.Storage.Type.Map, new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, new Substrate.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> WaitingInitStorageDefault
        /// Default value as hex string
        /// </summary>
        public static string WaitingInitStorageDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> WaitingInitStorage
        /// </summary>
        public async Task<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId>> WaitingInitStorage(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId key, string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.WaitingInitStorageParams(key);
            var result = await _client.GetStorageAsync<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId>>(parameters, blockhash, token);
            return result;
        }
        
        /// <summary>
        /// >> PausedProgramStorageParams
        /// </summary>
        public static string PausedProgramStorageParams(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId key)
        {
            return RequestGenerator.GetStorage("GearProgram", "PausedProgramStorage", Substrate.NetApi.Model.Meta.Storage.Type.Map, new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, new Substrate.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> PausedProgramStorageDefault
        /// Default value as hex string
        /// </summary>
        public static string PausedProgramStorageDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> PausedProgramStorage
        /// </summary>
        public async Task<Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Model.Types.Primitive.U32, Substrate.Vara.NET.NetApiExt.Generated.Model.primitive_types.H256>> PausedProgramStorage(Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId key, string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.PausedProgramStorageParams(key);
            var result = await _client.GetStorageAsync<Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Model.Types.Primitive.U32, Substrate.Vara.NET.NetApiExt.Generated.Model.primitive_types.H256>>(parameters, blockhash, token);
            return result;
        }
        
        /// <summary>
        /// >> ResumeSessionsNonceParams
        /// </summary>
        public static string ResumeSessionsNonceParams()
        {
            return RequestGenerator.GetStorage("GearProgram", "ResumeSessionsNonce", Substrate.NetApi.Model.Meta.Storage.Type.Plain);
        }
        
        /// <summary>
        /// >> ResumeSessionsNonceDefault
        /// Default value as hex string
        /// </summary>
        public static string ResumeSessionsNonceDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> ResumeSessionsNonce
        /// </summary>
        public async Task<Substrate.NetApi.Model.Types.Primitive.U128> ResumeSessionsNonce(string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.ResumeSessionsNonceParams();
            var result = await _client.GetStorageAsync<Substrate.NetApi.Model.Types.Primitive.U128>(parameters, blockhash, token);
            return result;
        }
        
        /// <summary>
        /// >> ResumeSessionsParams
        /// </summary>
        public static string ResumeSessionsParams(Substrate.NetApi.Model.Types.Primitive.U128 key)
        {
            return RequestGenerator.GetStorage("GearProgram", "ResumeSessions", Substrate.NetApi.Model.Meta.Storage.Type.Map, new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, new Substrate.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> ResumeSessionsDefault
        /// Default value as hex string
        /// </summary>
        public static string ResumeSessionsDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> ResumeSessions
        /// </summary>
        public async Task<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.paused_program_storage.ResumeSession> ResumeSessions(Substrate.NetApi.Model.Types.Primitive.U128 key, string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.ResumeSessionsParams(key);
            var result = await _client.GetStorageAsync<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.paused_program_storage.ResumeSession>(parameters, blockhash, token);
            return result;
        }
        
        /// <summary>
        /// >> SessionMemoryPagesParams
        /// </summary>
        public static string SessionMemoryPagesParams(Substrate.NetApi.Model.Types.Primitive.U128 key)
        {
            return RequestGenerator.GetStorage("GearProgram", "SessionMemoryPages", Substrate.NetApi.Model.Meta.Storage.Type.Map, new Substrate.NetApi.Model.Meta.Storage.Hasher[] {
                        Substrate.NetApi.Model.Meta.Storage.Hasher.Identity}, new Substrate.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> SessionMemoryPagesDefault
        /// Default value as hex string
        /// </summary>
        public static string SessionMemoryPagesDefault()
        {
            return "0x00";
        }
        
        /// <summary>
        /// >> SessionMemoryPages
        /// </summary>
        public async Task<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.pages.GearPage, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.memory.PageBuf>>> SessionMemoryPages(Substrate.NetApi.Model.Types.Primitive.U128 key, string blockhash, CancellationToken token)
        {
            string parameters = GearProgramStorage.SessionMemoryPagesParams(key);
            var result = await _client.GetStorageAsync<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.pages.GearPage, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.memory.PageBuf>>>(parameters, blockhash, token);
            return result;
        }
    }
    
    /// <summary>
    /// >> GearProgramCalls
    /// </summary>
    public sealed class GearProgramCalls
    {
    }
    
    /// <summary>
    /// >> GearProgramConstants
    /// </summary>
    public sealed class GearProgramConstants
    {
    }
    
    /// <summary>
    /// >> GearProgramErrors
    /// </summary>
    public enum GearProgramErrors
    {
        
        /// <summary>
        /// >> DuplicateItem
        /// </summary>
        DuplicateItem,
        
        /// <summary>
        /// >> ProgramNotFound
        /// </summary>
        ProgramNotFound,
        
        /// <summary>
        /// >> NotActiveProgram
        /// </summary>
        NotActiveProgram,
        
        /// <summary>
        /// >> CannotFindDataForPage
        /// </summary>
        CannotFindDataForPage,
        
        /// <summary>
        /// >> ResumeSessionNotFound
        /// </summary>
        ResumeSessionNotFound,
        
        /// <summary>
        /// >> NotSessionOwner
        /// </summary>
        NotSessionOwner,
        
        /// <summary>
        /// >> ResumeSessionFailed
        /// </summary>
        ResumeSessionFailed,
        
        /// <summary>
        /// >> ProgramCodeNotFound
        /// </summary>
        ProgramCodeNotFound,
        
        /// <summary>
        /// >> DuplicateResumeSession
        /// </summary>
        DuplicateResumeSession,
    }
}
