//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_ranked_collective.pallet
{
    
    
    /// <summary>
    /// >> Event
    /// The `Event` enum of this pallet
    /// </summary>
    public enum Event
    {
        
        /// <summary>
        /// >> MemberAdded
        /// A member `who` has been added.
        /// </summary>
        MemberAdded = 0,
        
        /// <summary>
        /// >> RankChanged
        /// The member `who`se rank has been changed to the given `rank`.
        /// </summary>
        RankChanged = 1,
        
        /// <summary>
        /// >> MemberRemoved
        /// The member `who` of given `rank` has been removed from the collective.
        /// </summary>
        MemberRemoved = 2,
        
        /// <summary>
        /// >> Voted
        /// The member `who` has voted for the `poll` with the given `vote` leading to an updated
        /// `tally`.
        /// </summary>
        Voted = 3,
    }
    
    /// <summary>
    /// >> 279 - Variant[pallet_ranked_collective.pallet.Event]
    /// The `Event` enum of this pallet
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.NetApi.Model.Types.Primitive.U16>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.NetApi.Model.Types.Primitive.U16>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.NetApi.Model.Types.Primitive.U32, Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_ranked_collective.EnumVoteRecord, Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_ranked_collective.Tally>>
    {
    }
}
