//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.vara_runtime
{
    
    
    /// <summary>
    /// >> OriginCaller
    /// </summary>
    public enum OriginCaller
    {
        
        /// <summary>
        /// >> system
        /// </summary>
        system = 0,
        
        /// <summary>
        /// >> Origins
        /// </summary>
        Origins = 20,
        
        /// <summary>
        /// >> Void
        /// </summary>
        Void = 2,
    }
    
    /// <summary>
    /// >> 119 - Variant[vara_runtime.OriginCaller]
    /// </summary>
    public sealed class EnumOriginCaller : BaseEnumExt<OriginCaller, Substrate.Vara.NET.NetApiExt.Generated.Model.frame_support.dispatch.EnumRawOrigin, BaseVoid, Substrate.NetApi.Model.Types.Base.BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, BaseVoid, Substrate.Vara.NET.NetApiExt.Generated.Model.vara_runtime.governance.origins.pallet_custom_origins.EnumOrigin>
    {
    }
}
