//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_gear.pallet
{
    
    
    /// <summary>
    /// >> Event
    /// The `Event` enum of this pallet
    /// </summary>
    public enum Event
    {
        
        /// <summary>
        /// >> MessageQueued
        /// User sends message to program, which was successfully
        /// added to the Gear message queue.
        /// </summary>
        MessageQueued = 0,
        
        /// <summary>
        /// >> UserMessageSent
        /// Somebody sent a message to the user.
        /// </summary>
        UserMessageSent = 1,
        
        /// <summary>
        /// >> UserMessageRead
        /// Message marked as "read" and removes it from `Mailbox`.
        /// This event only affects messages that were
        /// already inserted in `Mailbox`.
        /// </summary>
        UserMessageRead = 2,
        
        /// <summary>
        /// >> MessagesDispatched
        /// The result of processing the messages within the block.
        /// </summary>
        MessagesDispatched = 3,
        
        /// <summary>
        /// >> MessageWaited
        /// Messages execution delayed (waited) and successfully
        /// added to gear waitlist.
        /// </summary>
        MessageWaited = 4,
        
        /// <summary>
        /// >> MessageWoken
        /// Message is ready to continue its execution
        /// and was removed from `Waitlist`.
        /// </summary>
        MessageWoken = 5,
        
        /// <summary>
        /// >> CodeChanged
        /// Any data related to program codes changed.
        /// </summary>
        CodeChanged = 6,
        
        /// <summary>
        /// >> ProgramChanged
        /// Any data related to programs changed.
        /// </summary>
        ProgramChanged = 7,
        
        /// <summary>
        /// >> QueueNotProcessed
        /// The pseudo-inherent extrinsic that runs queue processing rolled back or not executed.
        /// </summary>
        QueueNotProcessed = 8,
        
        /// <summary>
        /// >> ProgramResumeSessionStarted
        /// Program resume session has been started.
        /// </summary>
        ProgramResumeSessionStarted = 9,
    }
    
    /// <summary>
    /// >> 303 - Variant[pallet_gear.pallet.Event]
    /// The `Event` enum of this pallet
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId, Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.@event.EnumMessageEntry>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.message.user.UserMessage, Substrate.NetApi.Model.Types.Base.BaseOpt<Substrate.NetApi.Model.Types.Primitive.U32>>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.@event.EnumReason>, BaseTuple<Substrate.NetApi.Model.Types.Primitive.U32, Substrate.Vara.NET.NetApiExt.Generated.Types.Base.BTreeMapT1, Substrate.Vara.NET.NetApiExt.Generated.Types.Base.BTreeSetT2>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId, Substrate.NetApi.Model.Types.Base.BaseOpt<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.gas_provider.node.EnumGasNodeId>, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.@event.EnumReason, Substrate.NetApi.Model.Types.Primitive.U32>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.@event.EnumReason>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.@event.EnumCodeChangeKind>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.@event.EnumProgramChangeKind>, BaseVoid, BaseTuple<Substrate.NetApi.Model.Types.Primitive.U128, Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.NetApi.Model.Types.Primitive.U32>>
    {
    }
}
