//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_gear_voucher
{
    
    
    /// <summary>
    /// >> PrepaidCall
    /// </summary>
    public enum PrepaidCall
    {
        
        /// <summary>
        /// >> SendMessage
        /// </summary>
        SendMessage = 0,
        
        /// <summary>
        /// >> SendReply
        /// </summary>
        SendReply = 1,
    }
    
    /// <summary>
    /// >> 276 - Variant[pallet_gear_voucher.PrepaidCall]
    /// </summary>
    public sealed class EnumPrepaidCall : BaseEnumExt<PrepaidCall, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>, Substrate.NetApi.Model.Types.Primitive.U64, Substrate.NetApi.Model.Types.Primitive.U128, Substrate.NetApi.Model.Types.Primitive.Bool>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId, Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>, Substrate.NetApi.Model.Types.Primitive.U64, Substrate.NetApi.Model.Types.Primitive.U128, Substrate.NetApi.Model.Types.Primitive.Bool>>
    {
    }
}
