//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_gear_voucher.pallet
{
    
    
    /// <summary>
    /// >> Call
    /// Contains a variant per dispatchable extrinsic that this pallet has.
    /// </summary>
    public enum Call
    {
        
        /// <summary>
        /// >> issue
        /// See [`Pallet::issue`].
        /// </summary>
        issue = 0,
        
        /// <summary>
        /// >> call
        /// See [`Pallet::call`].
        /// </summary>
        call = 1,
    }
    
    /// <summary>
    /// >> 275 - Variant[pallet_gear_voucher.pallet.Call]
    /// Contains a variant per dispatchable extrinsic that this pallet has.
    /// </summary>
    public sealed class EnumCall : BaseEnumExt<Call, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.sp_runtime.multiaddress.EnumMultiAddress, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.NetApi.Model.Types.Primitive.U128>, Substrate.Vara.NET.NetApiExt.Generated.Model.pallet_gear_voucher.EnumPrepaidCall>
    {
    }
}
