//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.@event
{
    
    
    /// <summary>
    /// >> Reason
    /// </summary>
    public enum Reason
    {
        
        /// <summary>
        /// >> Runtime
        /// </summary>
        Runtime = 0,
        
        /// <summary>
        /// >> System
        /// </summary>
        System = 1,
    }
    
    /// <summary>
    /// >> 330 - Variant[gear_common.event.Reason]
    /// </summary>
    public sealed class EnumReason : BaseEnumExt<Reason, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.@event.EnumMessageWokenRuntimeReason, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.@event.EnumMessageWokenSystemReason>
    {
    }
}
