//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.Vara.NET.NetApiExt.Generated.Model.gear_common.scheduler.task
{
    
    
    /// <summary>
    /// >> ScheduledTask
    /// </summary>
    public enum ScheduledTask
    {
        
        /// <summary>
        /// >> PauseProgram
        /// </summary>
        PauseProgram = 0,
        
        /// <summary>
        /// >> RemoveCode
        /// </summary>
        RemoveCode = 1,
        
        /// <summary>
        /// >> RemoveFromMailbox
        /// </summary>
        RemoveFromMailbox = 2,
        
        /// <summary>
        /// >> RemoveFromWaitlist
        /// </summary>
        RemoveFromWaitlist = 3,
        
        /// <summary>
        /// >> RemovePausedProgram
        /// </summary>
        RemovePausedProgram = 4,
        
        /// <summary>
        /// >> WakeMessage
        /// </summary>
        WakeMessage = 5,
        
        /// <summary>
        /// >> SendDispatch
        /// </summary>
        SendDispatch = 6,
        
        /// <summary>
        /// >> SendUserMessage
        /// </summary>
        SendUserMessage = 7,
        
        /// <summary>
        /// >> RemoveGasReservation
        /// </summary>
        RemoveGasReservation = 8,
        
        /// <summary>
        /// >> RemoveResumeSession
        /// </summary>
        RemoveResumeSession = 9,
    }
    
    /// <summary>
    /// >> 592 - Variant[gear_common.scheduler.task.ScheduledTask]
    /// </summary>
    public sealed class EnumScheduledTask : BaseEnumExt<ScheduledTask, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.CodeId, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.sp_core.crypto.AccountId32, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId>, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId>, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.MessageId, Substrate.NetApi.Model.Types.Primitive.Bool>, BaseTuple<Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ProgramId, Substrate.Vara.NET.NetApiExt.Generated.Model.gear_core.ids.ReservationId>, Substrate.NetApi.Model.Types.Primitive.U128>
    {
    }
}
